name: Notify Google Chat

on:
  push:
    branches: ["main", "Release", "Stage", "Development"]
  pull_request:
    branches: ["main", "Release", "Stage", "Development"]
    types: [opened, reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Get commit message
        id: commitMsg
        run: echo "msg=$(git log -1 --pretty=format:%s)" >> $GITHUB_OUTPUT

      - name: Get changed files
        id: changes
        run: |
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            echo "count=$(git diff --name-only HEAD^ HEAD | wc -l)" >> $GITHUB_OUTPUT
          else
            echo "count=0" >> $GITHUB_OUTPUT
          fi

      - name: Build JSON message
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          printf '%s\n' "{
            \"text\": \"Repository: ${{ github.repository }}\\nBranch: ${{ github.ref_name }}\\nTriggered By: ${{ github.actor }}\\n\\nCommit Message: ${{ steps.commitMsg.outputs.msg }}\\nCommit SHA: ${{ github.sha }}\\nChanged Files Count: ${{ steps.changes.outputs.count }}\\n\\nTimestamp (UTC): $TIMESTAMP\\n\\nView Workflow:\\nhttps://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
          }" > message.json

      - name: Send to Google Chat
        env:
          RAW_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
        run: |
          # FIX WEBHOOK URL IF MULTILINE
          WEBHOOK_URL=$(echo "$RAW_URL" | tr -d '\n' | tr -d '\r' | tr -d ' ')
          
          echo "Using cleaned webhook URL:"
          echo "$WEBHOOK_URL"

          curl -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d @message.json
